### ISSUE TITLE
Installation error on step 'pip install .'

### ISSUE THREAD

**Issue by RishiPandey06** [FeTS-AI/Challenge#188]
Hi,
I am getting this error while on the step on pip install . given in the readme.
I have been trying to solve this for the past 1 week I do not understand the cause for this error. 
![error image](https://github.com/FeTS-AI/Challenge/assets/22467435/b9d767c5-e535-4057-8ee1-b43a0f084586)

Here's my pytorch config:
![image](https://github.com/FeTS-AI/Challenge/assets/22467435/3bb4c805-b803-4a86-8986-90b944ddb9a6)

Please let me know what I might be doing wrong or the changes I need to make, I'm running the exact same code mentioned in the readme even for the venv setup.

Thank you

**Comment by mzenk** [comment]
Hi Rishy, I assume you're talking about the [task 1 readme](https://github.com/FeTS-AI/Challenge/blob/main/Task_1/README.md). @RishiPandey06 can you send the complete output of the pip install command instead of a screenshot?
Maybe someone from the task-1 team help? (e.g. @brandon-edwards @psfoley; maybe also @Geeks-Sid because the screenshot looks similar to an error reported in issue #172)?
Since the challenge is currently not active, however, I'm not sure if someone from the Task-1 team is available soon, unfortunately...

**Comment by sunyeongan** [comment]
@RishiPandey06  
Did you solve this problem? I'm experiencing the same problem.

**Comment by PandeyRishiV** [comment]
@sunyeongan No, sadly I had to leave this project and create a federated learning model / env of my own. You could use tensorflows federated learning library to implement the same

**Comment by psfoley** [comment]
@RishiPandey06 @sunyeongan - this seems to be a compatibility bug with Windows for OpenFL (OpenFL experimentally supports Windows, but issues like this do come up occassionally). If possible to move forward, I would recommend migrating to Linux while my team looks into a fix.

**Comment by sunyeongan** [comment]
hi @psfoley 
Following your advice, I am running the code in WSL on Windows in Ubuntu Linux 22.04 environment.
however
`pip install .`
An error occurs in the command.
<img width="953" alt="image" src="https://github.com/FeTS-AI/Challenge/assets/44018024/985f5d66-e06a-444d-90e3-25d5a8ed920e">

Perhaps this issue is  https://github.com/FeTS-AI/Challenge/issues/172#issuecomment-2143756215 is connected to
 https://github.com/FeTS-AI/Challenge/blob/524d6b9f489ba852d601a437839abd937e5cab89/Task_1/setup.py#L32 was changed to `GANDLF @ git+https://github.com/sunyeongan/GaNDLF.git@ff6417f19c4da0eb64c50afb5d436887203f63c8',` 

With this change it will run. But I wonder if this is right

**Comment by kta-intel** [comment]
Hey @RishiPandey06 @sunyeongan

Re: Windows installation issue - can you try pinning OpenFL==v1.5 in the `setup.py`?
i.e. change
https://github.com/FeTS-AI/Challenge/blob/524d6b9f489ba852d601a437839abd937e5cab89/Task_1/setup.py#L31
to `openfl @ git+https://github.com/intel/openfl.git@v1.5`

**Comment by kta-intel** [comment]
> I am running the code in WSL on Windows in Ubuntu Linux 22.04 environment. however `pip install .` An error occurs in the command. <img alt="image" width="953" src="https://private-user-images.githubusercontent.com/44018024/335851114-985f5d66-e06a-444d-90e3-25d5a8ed920e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTMzNTMsIm5iZiI6MTcxNzYxMzA1MywicGF0aCI6Ii80NDAxODAyNC8zMzU4NTExMTQtOTg1ZjVkNjYtZTA2YS00NDRkLTkwZTMtMjVkNWE4ZWQ5MjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE4NDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NGNjMjNkMzVjZjUwZGVhODlkYTVhYzE4YWVmNmYzOWM2Njc5YjVlMzU2ZjI4ZDc0OTM2NmFiOWRhZTY0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aACBJXPH4Z83c6IaaCAEG9gZYqgUyBq3A6bSFw6wMPY">
> 
> Perhaps this issue is [#172 (comment)](https://github.com/FeTS-AI/Challenge/issues/172#issuecomment-2143756215) is connected to
> 
> https://github.com/FeTS-AI/Challenge/blob/524d6b9f489ba852d601a437839abd937e5cab89/Task_1/setup.py#L32
> 
> was changed to `GANDLF @ git+https://github.com/sunyeongan/GaNDLF.git@ff6417f19c4da0eb64c50afb5d436887203f63c8',`
> With this change it will run. But I wonder if this is right


Hmm, I did not run into this issue on my end. I wonder if it's a network issue. Though maybe not if you aren't running into issues cloning and installing other repos from source.

Can you try updating the URL?
https://github.com/FeTS-AI/Challenge/blob/524d6b9f489ba852d601a437839abd937e5cab89/Task_1/setup.py#L32
to `GANDLF @ git+https://github.com/mlcommons/GaNDLF.git@e4d0d4bfdf4076130817001a98dfb90189956278`

Also might be helpful to update the commit to: https://github.com/mlcommons/GaNDLF/commit/f13fb9cb9c9ceb6490611ffab3469bcdb3d6f956 (same commit but contained within that repo)

**Comment by sunyeongan** [comment]
thank you for the reply. @kta-intel 
It wasn't a network problem.

https://github.com/FeTS-AI/Challenge/blob/524d6b9f489ba852d601a437839abd937e5cab89/Task_1/setup.py#L30C5-L34C7


- git clone https://github.com/intel/openfl.git
- cd openfl
- git checkout f4b28d710e2be31cdfa7487fdb4e8cb3a1387a5f
- pip install .

**Comment by kta-intel** [comment]
> thank you for the reply. @kta-intel It wasn't a network problem.
> 
> https://github.com/FeTS-AI/Challenge/blob/524d6b9f489ba852d601a437839abd937e5cab89/Task_1/setup.py#L30C5-L34C7
> 
> I solved the problem by installing each library as follows.
> 
> * git clone https://github.com/intel/openfl.git
> * cd openfl
> * git checkout f4b28d710e2be31cdfa7487fdb4e8cb3a1387a5f
> * pip install .

Hey @sunyeongan, Thanks for the instructions. I just wanted to confirm something: did manually checking out and installing from that commit resolve the UnicodeDecodeError issue on Windows for you or was this in WSL/Linux?

**Comment by sunyeongan** [comment]
@kta-intel
