### ISSUE TITLE
中国IP安装Singularity时，出现超时问题，我踩过了，避免大家踩坑吧

### ISSUE THREAD

**Issue by JalexDooo** [FETS-AI/Challenge#37]
### 踩坑两天。超时问题使用ss or clash在控制台代理都不可行，安装全凭运气，因为GO语言安装代理在中国是阻塞的。服务器上安装成功了，linux虚拟机失败了。

- 运行`./mconfig`后，运行`cd builddir` and `make`时出现超时。

- 进入`builddir`文件夹

- 文本打开`Makefile`文件

- 找到并修改修改`GOPROXY := https://proxy.golang.org`改为`GOPROXY := https://proxy.golang.cn`

**Comment by mzenk** [comment]
Sorry, I can't read most of your message. Is this an issue with this repo? Otherwise the discussions page is the more appropriate place for this thread.
If your question is why we do not use docker: It makes it easier for us in our evaluation system and does not seem a big burden for the participants. Feel free to re-open if there is an issue with the code.

**Comment by sarthakpati** [comment]
> So, why not use Docker? emmmm...

Thank you for your interest in the FeTS challenge, @JalexDooo.

In addition to what @mzenk said, I would like to chime in with a few additional articles to provide clarity with regards of using Singularity and not Docker because of security concerns:

- https://www.freecodecamp.org/news/7-cases-when-not-to-use-docker/
- https://www.kdnuggets.com/2020/10/use-docker-anymore.html
- https://towardsdatascience.com/its-time-to-say-goodbye-to-docker-5cfec8eff833

**Comment by JalexDooo** [comment]
Hi,

First, thank you very much for your work and contribution.

I ran into a timeout problem when i install the Singularity (make && make install). The dependency management tool of Go did not work with China IP and the network was blocked.

I spend almost 2 days to deal with the problem through change a code in the `Makefile` `GOPROXY := https://proxy.golang.org` to `GOPROXY := https://proxy.golang.cn`.

Therefore, I strongly suggest that Chinese researchers and competitors can be informed of this situation through this **Issue**.

**Thanks for your consideration.** @sarthakpati @mzenk

**Comment by mzenk** [comment]
Hi @JalexDooo,
thank you for the clarification. I did not anticipate this problem with China IP and am sorry for the inconvenience!
If I understand correctly, you found a solution yourself by changing the `GOPROXY`? That's a great initiative and you are absolutely right that this should be documented.
Since I cannot read the title of this issue, I would like to ask you: do you think this issue is visible enough for Chinese researchers? Or should I add a note to the readme or discussion section?
Thank you for your contribution!

**Comment by JalexDooo** [comment]
The issue is visible enough for Chinese researchers.

Thanks for your reply! @mzenk
